# coding=utf8

from sae.const import (MYSQL_HOST, MYSQL_HOST_S,
    MYSQL_PORT, MYSQL_USER, MYSQL_PASS, MYSQL_DB
)

# SQLALCHEMY_DATABASE_URI = 'mysql://root:123456@127.0.0.1/test'
SQLALCHEMY_DATABASE_URI = 'mysql://' + MYSQL_USER + ':' + MYSQL_PASS + '@' + MYSQL_HOST + ':' + MYSQL_PORT + '/' + MYSQL_DB
SQLALCHEMY_TRACK_MODIFICATIONS = True

PAGE_SIZE = 50
TABLE_NAME = 'ticketinfo'
SINGLE_PRICE = 20